### ISSUE TITLE
Various sidebar improvements.

### ISSUE THREAD

**Issue by dRamosCode** [dRamosCode/kawasaki-as-vscode-extension#1]
**New features**

- Program list refresh.
  - Update the program list if new programs are coded.
- Program position refresh.
  - If new code is written but the program tree is not refreshed, jumping to program or copying does not work properly.
- New sidebar top button to get back and forward to last position before jumping to definition or program.
  - After jumping to definition or program, remember the last X positions and get back or forward in the jump list.
  - Possible sidebar section with a list of jumps executed.

**Comment by yelangtangtang** [comment]
The first line is;; Or indent keywords

In the future, as long as there are two or more spaces, they will inevitably be indented.

**Comment by yelangtangtang** [comment]
![Uploading 无标题.jpg…]()

**Comment by yelangtangtang** [comment]
![无标题](https://github.com/dRamosCode/kawasaki-as-vscode-extension/assets/114210737/27bd02a1-445f-4c96-82fb-9862135ea80e)
