### ISSUE TITLE
Problem with colours for people with colour blindness.

### ISSUE THREAD

**Issue by urtziDV** [dRamosCode/kawasaki-as-vscode-extension#2]
It would be nice to be able to have adjustments for colours, as a person with colour blindness may have problems reading texts correctly. For example the comments, which have the colour rgb(195, 232, 141), it would be nice to be able to change them to rgb(106, 153, 85) for a correct distinction regarding the colour of the instructions like "SIGNAL", "LMOVE", "JMOVE"...

Thanks!

**Comment by dRamosCode** [comment]
Thanks @urtziDV for the feedback.

**Color customization has been added to version 1.0.4 of the extension to solve this issue.**

### Changes v1.0.4
- Added color customization via user settings.
  - Independent customization for light and dark themes.
- Changed default dark theme comment color from rgb(195, 232, 141) to rgb(106, 153, 85)  for better differentiation.
