### ISSUE TITLE
 Change syntax highlighting color

### ISSUE THREAD

**Issue by WONJAEMUN** [dRamosCode/kawasaki-as-vscode-extension#4]
Hello, I am using Kawasaki AS Language with VSCODE. However, as shown in the picture, the color is only blue or purple. Even if I want to change the color, it does not change. I would like to know how. thank you
![스크린샷 2024-04-26 170737](https://github.com/dRamosCode/kawasaki-as-vscode-extension/assets/166085132/674ae0b1-982f-4d0b-9c73-955cf823daef)

**Comment by dRamosCode** [comment]
Hi,

Kawasaki AS Language syntax highlighting should be on immediately after installing the extension. However, I've seen some issues related to extension incompatibility. Do you or did you have any other Kawasaki Language Extension installed? If so, try uninstalling the extension to check if that's the case.

Let's also check a few things:
- Check that the language selected for the file is `Kawasaki AS` and nothing different.
- Check if changing theme colors in `Settings/Extensions/Kawasaki AS Language` has effect in the editor.

**Comment by WONJAEMUN** [comment]
![스크린샷 2024-05-09 100726](https://github.com/dRamosCode/kawasaki-as-vscode-extension/assets/166085132/722df894-f989-4595-8798-4bfb3e83ad60)
![스크린샷 2024-05-09 100737](https://github.com/dRamosCode/kawasaki-as-vscode-extension/assets/166085132/3d05e030-c2dc-4688-8ff5-ca80cb50e847)
Thanks for your answer. Color issue fixed. I'm also curious about the behavior when using Ctrl+click in the GOTO command or CALL command. How do I select text after a period appears? The text after the underline is selected differently than the period.

**Comment by dRamosCode** [comment]
Glad to hear the color issue is fixed. Could you please provide the steps followed to solve it, so no one else bumps into this problem later?

**Comment by WONJAEMUN** [comment]
I don't know if the way I did it is correct. After setting up the working folder, a .vscode folder was created and the color problem was resolved.

**Comment by dRamosCode** [comment]
Ok, thanks for the info. Marking this issue as closed now.
